### PR TITLE
Update page.codeberg.libre_menu_editor.LibreMenuEditor.yml

### PR DESCRIPTION
**Pull request by libre-menu-editor**

### CODE REVIEW

**Comment by libre-menu-editor** [comment]
bot, build page.codeberg.libre_menu_editor.LibreMenuEditor

**Comment by libre-menu-editor** [comment]
bot, build page.codeberg.libre_menu_editor.LibreMenuEditor

**Comment by libre-menu-editor** [comment]
bot, build page.codeberg.libre_menu_editor.LibreMenuEditor

**Comment by bbhtt** [comment]
it's going to take a while to be up

**Comment by bbhtt** [comment]
You can check using:

```bash
curl -s https://flathub.org/api/v2/exceptions|jq '."page.codeberg.libre_menu_editor.LibreMenuEditor"'
```

I'll add this to the docs.

**Comment by libre-menu-editor** [comment]
bot, build page.codeberg.libre_menu_editor.LibreMenuEditor

**Comment by libre-menu-editor** [comment]
@bbhtt Thank you for the information.

(PS: The last attempt was due to me misreading the output of your command)

**Comment by libre-menu-editor** [comment]
bot, build page.codeberg.libre_menu_editor.LibreMenuEditor

**Comment by libre-menu-editor** [comment]
bot, build page.codeberg.libre_menu_editor.LibreMenuEditor

**Pull request merged**
